### ISSUE TITLE
Simulation results related to Rayleigh fading channel

### ISSUE THREAD

**Issue by JS2498** [ortalagiv/Learn-to-Rapidly-Optimize-Hybrid-Precoding#1]
Do the simulation results given in the research paper obtained for Rayleigh fading channel (entries of the channel matrix has to be complex) or considering a channel matrix with the matrix entries from i.i.d Gaussian distribution (real values)? 

When I made the changes to the code to make it suitable for Rayleigh fading channel (complex entries), I was unable to replicate the exact results.

Can you please clarify on this?

**Comment by ortalagiv** [comment]
Hello, thank you for your question.
In the paper, we present simulations for real-valued channels (Rayleigh) and for complex-valued channels (QuaDRiGa). The channel realizations used in this repository are real-valued, though the code is suitable for both cases.
